# Generated by Django 4.1.3 on 2022-12-07 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.TextField(verbose_name="Вопрос")),
            ],
        ),
        migrations.CreateModel(
            name="SetQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("topic", models.CharField(max_length=50, verbose_name="Название/Тема теста")),
                (
                    "date_publication",
                    models.DateField(auto_now_add=True, verbose_name="Дата публикации"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Statistic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("right_answer", models.IntegerField(default=0, verbose_name="Верные ответы")),
                ("wrong_answer", models.IntegerField(default=0, verbose_name="Неверные ответы")),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="Пройдено/ не пройдено"),
                ),
                ("date_pass", models.DateField(auto_now=True, verbose_name="Дата прохождения")),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="online_testing.setquestionnaire",
                        verbose_name="Название/Тема теста",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OptionAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "option",
                    models.TextField(
                        choices=[("True", "Верно"), ("False", "Неверно")], verbose_name="Ответ"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="online_testing.listquestion",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="listquestion",
            name="questionnaire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="online_testing.setquestionnaire",
                verbose_name="Название/Тема теста",
            ),
        ),
    ]
