# Generated by Django 4.1.5 on 2023-01-12 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("online_testing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.CharField(max_length=250, verbose_name="Вопрос")),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
                "ordering": ("questionnaire_name__id", "question"),
            },
        ),
        migrations.CreateModel(
            name="Questionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "topic_questionnaire",
                    models.CharField(max_length=100, verbose_name="Тема тестового набора"),
                ),
                (
                    "status_active",
                    models.CharField(
                        choices=[("1", "Да"), ("0", "Нет")],
                        default="1",
                        max_length=3,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "date_publication",
                    models.DateField(auto_now_add=True, verbose_name="Дата публикации"),
                ),
            ],
            options={
                "verbose_name": "Тестовый набор",
                "verbose_name_plural": "Тестовые наборы",
            },
        ),
        migrations.AlterModelOptions(
            name="optionanswer",
            options={
                "ordering": ("question_name__id", "option"),
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответов",
            },
        ),
        migrations.AlterModelOptions(
            name="statistic",
            options={
                "ordering": ("user", "questionnaire_name__id"),
                "verbose_name": "Статистика",
                "verbose_name_plural": "Статистики",
            },
        ),
        migrations.RemoveField(
            model_name="optionanswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="statistic",
            name="questionnaire",
        ),
        migrations.RemoveField(
            model_name="statistic",
            name="status",
        ),
        migrations.AddField(
            model_name="statistic",
            name="status_pass",
            field=models.BooleanField(default=False, verbose_name="Статус прохождения теста"),
        ),
        migrations.AlterField(
            model_name="optionanswer",
            name="option",
            field=models.CharField(
                choices=[("1", "Верно"), ("0", "Неверно")],
                default=None,
                max_length=10,
                verbose_name="Вариант ответа",
            ),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="date_pass",
            field=models.DateField(auto_now=True, verbose_name="Дата прохождения теста"),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="right_answer",
            field=models.IntegerField(default=0, verbose_name="Верный ответ"),
        ),
        migrations.AlterField(
            model_name="statistic",
            name="wrong_answer",
            field=models.IntegerField(default=0, verbose_name="Неверный ответ"),
        ),
        migrations.DeleteModel(
            name="ListQuestion",
        ),
        migrations.DeleteModel(
            name="SetQuestionnaire",
        ),
        migrations.AddField(
            model_name="question",
            name="questionnaire_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="online_testing.questionnaire",
                verbose_name="Тема тестового набора",
            ),
        ),
        migrations.AddField(
            model_name="optionanswer",
            name="question_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="online_testing.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AddField(
            model_name="statistic",
            name="questionnaire_name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="online_testing.questionnaire",
                verbose_name="Название тестового набора",
            ),
        ),
    ]
